// <auto-generated />
using System;
using CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250610161921_Intital")]
    partial class Intital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD.Models.Entites.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Employes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            Gender = 0,
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Software Engineer",
                            LastName = "Doe",
                            PhoneNumber = "1234567890",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            Gender = 1,
                            HireDate = new DateTime(2019, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "QA Analyst",
                            LastName = "Smith",
                            PhoneNumber = "2345678901",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "robert.brown@example.com",
                            FirstName = "Robert",
                            Gender = 0,
                            HireDate = new DateTime(2018, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Project Manager",
                            LastName = "Brown",
                            PhoneNumber = "3456789012",
                            Salary = 90000m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Email = "emily.clark@example.com",
                            FirstName = "Emily",
                            Gender = 1,
                            HireDate = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "UX Designer",
                            LastName = "Clark",
                            PhoneNumber = "4567890123",
                            Salary = 70000m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            Email = "daniel.lee@example.com",
                            FirstName = "Daniel",
                            Gender = 0,
                            HireDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "DevOps Engineer",
                            LastName = "Lee",
                            PhoneNumber = "5678901234",
                            Salary = 80000m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            Email = "olivia.walker@example.com",
                            FirstName = "Olivia",
                            Gender = 1,
                            HireDate = new DateTime(2017, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobTitle = "HR Manager",
                            LastName = "Walker",
                            PhoneNumber = "6789012345",
                            Salary = 85000m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 7,
                            Email = "david.king@example.com",
                            FirstName = "David",
                            Gender = 0,
                            HireDate = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Network Engineer",
                            LastName = "King",
                            PhoneNumber = "7890123456",
                            Salary = 72000m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            Email = "sophia.allen@example.com",
                            FirstName = "Sophia",
                            Gender = 1,
                            HireDate = new DateTime(2016, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "System Analyst",
                            LastName = "Allen",
                            PhoneNumber = "8901234567",
                            Salary = 69000m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 9,
                            Email = "james.scott@example.com",
                            FirstName = "James",
                            Gender = 0,
                            HireDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "IT Support",
                            LastName = "Scott",
                            PhoneNumber = "9012345678",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 10,
                            Email = "grace.green@example.com",
                            FirstName = "Grace",
                            Gender = 1,
                            HireDate = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Security Analyst",
                            LastName = "Green",
                            PhoneNumber = "0123456789",
                            Salary = 78000m
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            Email = "aaron.young@example.com",
                            FirstName = "Aaron",
                            Gender = 0,
                            HireDate = new DateTime(2021, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Frontend Developer",
                            LastName = "Young",
                            PhoneNumber = "1231231234",
                            Salary = 73000m
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Email = "zoe.hill@example.com",
                            FirstName = "Zoe",
                            Gender = 1,
                            HireDate = new DateTime(2021, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Backend Developer",
                            LastName = "Hill",
                            PhoneNumber = "2342342345",
                            Salary = 77000m
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            Email = "ethan.wright@example.com",
                            FirstName = "Ethan",
                            Gender = 0,
                            HireDate = new DateTime(2015, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobTitle = "Database Admin",
                            LastName = "Wright",
                            PhoneNumber = "3453453456",
                            Salary = 88000m
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 4,
                            Email = "lily.lopez@example.com",
                            FirstName = "Lily",
                            Gender = 1,
                            HireDate = new DateTime(2018, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Mobile Developer",
                            LastName = "Lopez",
                            PhoneNumber = "4564564567",
                            Salary = 71000m
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 5,
                            Email = "henry.adams@example.com",
                            FirstName = "Henry",
                            Gender = 0,
                            HireDate = new DateTime(2019, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Business Analyst",
                            LastName = "Adams",
                            PhoneNumber = "5675675678",
                            Salary = 76000m
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 6,
                            Email = "ella.baker@example.com",
                            FirstName = "Ella",
                            Gender = 1,
                            HireDate = new DateTime(2017, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Tech Lead",
                            LastName = "Baker",
                            PhoneNumber = "6786786789",
                            Salary = 98000m
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 7,
                            Email = "logan.nelson@example.com",
                            FirstName = "Logan",
                            Gender = 0,
                            HireDate = new DateTime(2014, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Architect",
                            LastName = "Nelson",
                            PhoneNumber = "7897897890",
                            Salary = 102000m
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 8,
                            Email = "chloe.carter@example.com",
                            FirstName = "Chloe",
                            Gender = 1,
                            HireDate = new DateTime(2020, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Consultant",
                            LastName = "Carter",
                            PhoneNumber = "8908908901",
                            Salary = 85000m
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 9,
                            Email = "lucas.mitchell@example.com",
                            FirstName = "Lucas",
                            Gender = 0,
                            HireDate = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Trainer",
                            LastName = "Mitchell",
                            PhoneNumber = "9019019012",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 10,
                            Email = "ava.perez@example.com",
                            FirstName = "Ava",
                            Gender = 1,
                            HireDate = new DateTime(2023, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobTitle = "Content Strategist",
                            LastName = "Perez",
                            PhoneNumber = "0120120123",
                            Salary = 67000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
